name: educourse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/svg/7010826_3255307.svg
    - lib/assets/images/svg/2nd.svg
    - lib/assets/images/cata/Traced Image.png
    - lib/assets/images/cata/Traced Image55.png
    - lib/assets/images/cata/Vector.png
    - lib/assets/images/cata/Vector5.png

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Black.ttf
         - asset: assets/fonts/Poppins-SemiBold.ttf

     - family: Darlington
       fonts:
         - asset: assets/fonts/DarlingtonDemo-z8xjG.ttf

