name: todoadv2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.2
  font_awesome_flutter: ^9.2.0
  flutter_slidable: ^0.6.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Prfile.png
    - images/home.png
    - images/personal.png
    - images/work.png
    - images/Star.png
    - images/Task Done png.png
    - images/Task not Done.png
